name: Webhook

on:
  push:
  pull_request:
  pull_request_review:
  pull_request_review_comment:
  issues:
  issue_comment:
  schedule:
    - cron: '*/15 * * * *' 

jobs:
  send_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook
        uses: distributhor/webhook-action@master
        with:
          url: 'https://61ed-49-207-232-202.ngrok-free.app'
          method: 'POST'
          payload: '{"event": "${{ github.event_name }}", "payload": "${{ toJson(github.event) }}"}'
